### ISSUE TITLE
Text Animation is leaving text colored residue behind on Mobile. 

### ISSUE THREAD

**Issue by gtrman97** [maxeth/react-type-animation#17] opened 2023-01-24 22:36 UTC
It works fine on desktop, and even in the responsive design dev tools with a mobile phone selected. But when I open up the same link on my iPhone the text animation will leave little text colored dots on the screen and not clear them away. You can see what I mean by opening up this link with a smart phone: https://bug-tracker-2.netlify.app/sign-in

**Comment by maxeth** [comment] 2023-03-20 17:58
Hi, sorry for responding so late.

I can indeed also see those dots on an iPhone device, but it's honestly the first time seeing this. Also: I noticed that when you zoom in, they disappear.

If I visit the examples from the docs or other demos on an iPhone, there are no white dots, so this won't be a general/universal issue.

If you're still using/trying to use it:
- Are you applying any custom styles?
- Did you set a custom wrapper element?
- How does/do the parent element(s) of the `TypeAnimation` component look like?

**Comment by maxeth** [comment] 2023-06-10 13:12
Couldn't reproduce this, closing for now.

**Closed by maxeth** 2023-06-10 13:12 UTC

**Comment by maxeth** [comment] 2023-10-13 14:11
@bwong365 

Interesting... thanks for sharing.

There's one single code snippet responsible for manipulating the DOM directly in the animation: `requestAnimationFrame(() => (node.textContent = snippet))` so this must be some bug with the browsers.

Not sure what options we have to fix this. I'd expect `requestAnimationFrame` preventing these sort of visual bugs, but apparently it doesn't. 

I can try removing `requestAnimationFrame` or adding some css like `transform: translate3d(0, 0, 0);` to force hardware acceleration, or `will-change: auto;` or `unset` to encourage cpu rendering by the browser and see what it does.
